version: '3'

includes:
  python: ./provision/task/python.yml
  git: ./provision/task/git.yml
  go: ./provision/task/go.yml
  docs: ./provision/task/docs.yml
  gitflow: ./provision/task/gitflow.yml
  version: ./provision/task/version.yml
  docker: ./provision/task/docker.yml
  changelog: ./provision/task/changelog.yml
  sonar: ./provision/task/sonar.yml
  images:
    taskfile: ./images/Taskfile.yml
    dir: ./images

env:
  DOCKER:
    sh: docker -v
  PYTHON:
    sh: python --version
  APP_TAG:
    sh: git describe --tags $(git rev-list --tags --max-count=1) 2> /dev/null || echo "0.0.0"
  README_YAML: provision/generators/README.yaml
  README_TEMPLATE: provision/templates/README.tpl.md
  README_INCLUDES: file://

dotenv:
  - .env

vars:
  PROJECT_NAME: docker-template
  ORGANIZATION: hadenlabs
  DOCKER_ORGANIZATION: hadenlabs
  DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8
  DOCKER_IMAGE_NAME: docker-template
  DOCKER_TAG: 0.0.0
  REVIEWERS: luismayta
  PYTHON_VERSION: 3.9.2
  GIT_IGNORES: python,node,go,zsh
  README_FILE: README.md
  GIT_IGNORES_CUSTOM: >-
    bin
    TMP_CHANGELOG.md
    .task

tasks:
  default:
    deps:
      - task: check
    cmds:
      - cmd: echo Application {{.PROJECT_NAME}}
        silent: true
      - task: version:default
      - task: summary
      - cmd: task -l
    silent: true

  summary:
    desc: 'Summary information'
    cmds:
      - echo Docker available {{.DOCKER}}
    silent: true

  check:
    desc: 'Check all dependencies'
    deps:
      - python:check
      - changelog:check
      - git:check
      - go:check
      - gitflow:check
      - docs:check

  readme:
    run: once
    desc: Generate Readme
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_TEMPLATE}}
        --out {{.README_FILE}}
        --datasource config={{.README_YAML}}
        --datasource includes={{.README_INCLUDES}}

  prettier:
    run: once
    desc: Execute prettier files
    cmds:
      - >-
        prettier --config=.github/linters/prettier.config.js
        --ignore-path=.github/linters/.prettierignore
        '**/*.{js?(on),ts?(x),scss,md,y?(a)ml,gql,graphql?(s),less,mjml}'
        --write=true
        --list-different

  setup:
    desc: Setup dependences of project
    cmds:
      - task: python:setup
      - task: python:precommit
      - task: git:setup
      - task: go:setup
      - task: gitflow:setup

  environment:
    desc: Setup environment of project
    cmds:
      - task: python:environment

  build:docker:
    run: once
    desc: Build docker Image.
    cmds:
      - task: images:build

  push:docker:
    run: once
    desc: Push docker Image.
    deps:
      - build:docker
    cmds:
      - task: images:publish
